### ISSUE TITLE
How to run in VS Code ?

### ISSUE THREAD

**Issue by virtuamechanica** [gkjohnson/vscode-urdf-viewer#10]
Hello,

like in #7 , I would like to know how to use it in VS Code please ? 
You mentionned that we have to open this repo in VSC and run debug, but I really don't know which file of this repo to launch (it basically just opens a new VS code instance window). Sorry, I'm not aware of VSC extensions..

This tool could be very helpful for quickly debugging urdfs.
Thank you for your help and advises
Yvan

**Comment by gkjohnson** [comment]
This isn't a project I've put time or thought into for well over 5 years and tbh I don't recall how to use it. It likely no longer works but if you'd like to put time into updating it and adjusting the documentation I'm happy to take a look at PRs for the project.

> Sorry, I'm not aware of VSC extensions.

There should be plenty of documentation available online describing the VS Code extension API.

**Comment by yvanblanchard** [comment]
Thank you Garett.
I ntoiced that the extension no longer works (with vs code v1.89.0), getting an error message because of the missing of vscode.previewhtml command.
I think this command is deprecated and then should be replaced by  'webview API'.
I will try to find time to fix this.
